### PR TITLE
Update for new adaptable discovery feature

### PR DESCRIPTION
**Pull request by spikeekips**
The detailed feature can be found at https://github.com/bosnet/sebak/pull/705 .

### CODE REVIEW

**Comment by cmcm2222** [comment]
I will change documents based on you wrote down.

**Comment by spikeekips** [comment]
@cmcm2222 I can not understand you will change?

**Comment by cmcm2222** [comment]
I missed repo location. 
I think that you submit this pr to bosnet/sebak lol.

**Comment by spikeekips** [comment]
@cmcm2222 I see. We should move `bosnet/sebak` to this place at first. :)

**Pull request merged**
